import asyncio
import json
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from ..core.triage_graph import graph_builder
from ..intake_fsm import complete_intake, get_session_state
from ..db.supabase_client import get_supabase
from datetime import datetime

router = APIRouter()

# Global list of diagnostic clients
_diagnostic_clients = []

async def ping_task(websocket: WebSocket):
    try:
        while True:
            await asyncio.sleep(20)
            await websocket.send_text('{"type": "ping"}')
    except asyncio.CancelledError:
        pass
    except Exception:
        pass

async def _process_graph_event(websocket: WebSocket, event: dict, msg: str):
    """Process a single graph event and send appropriate responses to the client"""
    # Broadcast to diagnostics
    for diag_ws in _diagnostic_clients:
        try:
            await diag_ws.send_text(json.dumps({
                "type": "diagnostic_update",
                "node": list(event.keys())[0] if event else "unknown",
                "state": event[list(event.keys())[0]] if event else {}
            }))
        except:
            pass
                
    for node_name, node_state in event.items():
        if node_state.get("is_emergency"):
            await websocket.send_text(json.dumps({
                "type": "emergency",
                "content": node_state["messages"][-1] if node_state.get("messages") else "Emergency detected",
            }))
            return
        
        # Send metadata if available
        if node_state.get("department"):
            await websocket.send_text(json.dumps({
                "type": "message",
                "state": node_state.get("triage_level"),
                "meta": {
                    "specialty": node_state.get("department"),
                    "confidence": node_state.get("confidence"),
                    "confidence_label": f"{int(node_state.get('confidence', 0) * 100)}%" if node_state.get("confidence") else None,
                    "urgency": node_state.get("triage_level"),
                    "triage_level": node_state.get("triage_level"),
                    "triage_color": "red" if node_state.get("triage_level") == 1 else "orange" if node_state.get("triage_level") in [2, 3] else "green"
                }
            }))
        
        if "messages" in node_state and len(node_state["messages"]) > 0:
            # Send latest message
            last_msg = node_state["messages"][-1]
            # Only send if it's a new message generated by the system, not the user's msg
            if last_msg != msg and last_msg.strip():
                await websocket.send_text(json.dumps({
                    "type": "message",
                    "content": last_msg
                }))
                        
        if node_state.get("available_slots"):
            await websocket.send_text(json.dumps({
                "type": "message",
                "content": "Available appointment slots:"
            }))
            for slot in node_state["available_slots"]:
                await websocket.send_text(json.dumps({
                    "type": "message",
                    "content": f"Slot: {slot.get('start_time', 'TBD')}"
                }))

@router.websocket("/api/v1/ws/chat/{session_id}")
async def chat_websocket(websocket: WebSocket, session_id: str):
    await websocket.accept()
    ping = asyncio.create_task(ping_task(websocket))
    
    try:
        while True:
            data = await websocket.receive_text()
            payload = json.loads(data)
            
            # Handle intake form
            if payload.get("type") == "intake_form":
                patient_id = await complete_intake(
                    session_id,
                    payload.get("name"),
                    int(payload.get("age")),
                    payload.get("gender"),
                    payload.get("contact")
                )
                await websocket.send_text(json.dumps({
                    "type": "message", 
                    "content": "Thank you. What brings you in today? (Or you can choose an option below)",
                    "chips": ["Describe my symptoms", "Book by department", "Book with a specific doctor"]
                }))
                continue
            
            # Message
            if payload.get("type") == "message":
                msg = payload.get("content")
                
                # Check FSM state
                state = get_session_state(session_id)
                if not state or state["state"] != "INITIAL_SYMPTOM":
                    await websocket.send_text(json.dumps({"type": "error", "content": "Please complete intake first."}))
                    continue
                    
                await websocket.send_text(json.dumps({"type": "typing"}))
                
                # Invoke LangGraph - checkpointer restores persisted state on subsequent messages
                config = {"configurable": {"thread_id": session_id}}
                
                # Provide required fields for first message; checkpointer merges with persisted state on subsequent messages
                input_state = {
                    "session_id": session_id,
                    "patient_id": state["patient_id"],
                    "messages": [msg],
                    "is_emergency": False,
                }
                
                try:
                    async for event in graph_builder.astream(input_state, config=config, stream_mode="updates"):
                        await _process_graph_event(websocket, event, msg)
                except Exception as e:
                    import logging
                    logging.error(f"Graph streaming error: {e}")
                    await websocket.send_text(json.dumps({"type": "error", "content": f"Processing error: {str(e)}"}))
                
                # Mark typing as complete
                await websocket.send_text(json.dumps({"type": "stream_start"}))
                            
    except WebSocketDisconnect:
        pass
    except Exception as e:
        print(f"Chat WS error: {e}")
        try:
            await websocket.send_text(json.dumps({"type": "error", "content": "An error occurred."}))
        except:
            pass
    finally:
        ping.cancel()
