import asyncio
import json
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from ..core.triage_graph import graph_builder
from ..intake_fsm import complete_intake, get_session_state
from ..db.supabase_client import get_supabase
from datetime import datetime

router = APIRouter()

# Global list of diagnostic clients
_diagnostic_clients = []

async def ping_task(websocket: WebSocket):
    try:
        while True:
            await asyncio.sleep(20)
            await websocket.send_text('{"type": "ping"}')
    except asyncio.CancelledError:
        pass
    except Exception:
        pass

@router.websocket("/api/v1/ws/chat/{session_id}")
async def chat_websocket(websocket: WebSocket, session_id: str):
    await websocket.accept()
    ping = asyncio.create_task(ping_task(websocket))
    
    try:
        while True:
            data = await websocket.receive_text()
            payload = json.loads(data)
            
            # Handle intake form
            if payload.get("type") == "intake_form":
                patient_id = await complete_intake(
                    session_id,
                    payload.get("name"),
                    int(payload.get("age")),
                    payload.get("gender"),
                    payload.get("contact")
                )
                await websocket.send_text(json.dumps({
                    "type": "message", 
                    "content": "Thank you. What brings you in today? (Or you can choose an option below)",
                    "chips": ["Describe my symptoms", "Book by department", "Book with a specific doctor"]
                }))
                continue
            
            # Message
            if payload.get("type") == "message":
                msg = payload.get("content")
                
                # Check FSM state
                state = get_session_state(session_id)
                if not state or state["state"] != "INITIAL_SYMPTOM":
                    await websocket.send_text(json.dumps({"type": "error", "content": "Please complete intake first."}))
                    continue
                    
                await websocket.send_text(json.dumps({"type": "typing"}))
                
                # Invoke LangGraph
                config = {"configurable": {"thread_id": session_id}}
                
                # We need to construct the input state for the graph
                input_state = {
                    "session_id": session_id,
                    "patient_id": state["patient_id"],
                    "messages": [msg]
                }
                
                async for event in graph_builder.astream(input_state, config=config, stream_mode="updates"):
                    # Broadcast to diagnostics
                    for diag_ws in _diagnostic_clients:
                        try:
                            await diag_ws.send_text(json.dumps({
                                "type": "diagnostic_update",
                                "node": list(event.keys())[0],
                                "state": event[list(event.keys())[0]]
                            }))
                        except:
                            pass
                            
                    for node_name, node_state in event.items():
                        if node_state.get("is_emergency"):
                            await websocket.send_text(json.dumps({
                                "type": "emergency",
                                "message": node_state["messages"][-1],
                                "department": "Emergency Medicine"
                            }))
                            break # stop processing this event
                        
                        if "messages" in node_state and len(node_state["messages"]) > 0:
                            # Send latest message
                            last_msg = node_state["messages"][-1]
                            # Only send if it's a new message generated by the system, not the user's msg
                            if last_msg != msg:
                                await websocket.send_text(json.dumps({
                                    "type": "message",
                                    "content": last_msg
                                }))
                                
                        if node_state.get("available_slots"):
                            await websocket.send_text(json.dumps({
                                "type": "slots_offer",
                                "slots": node_state["available_slots"]
                            }))
                            
    except WebSocketDisconnect:
        pass
    except Exception as e:
        print(f"Chat WS error: {e}")
        try:
            await websocket.send_text(json.dumps({"type": "error", "content": "An error occurred."}))
        except:
            pass
    finally:
        ping.cancel()
